-- Generates MythicLoot/Data/SeasonLoot.lua from an exported SavedVariables file.
-- Usage: lua gen_seasonloot.lua <savedvars.lua> <out.lua>
local svPath, outPath = arg[1], arg[2]
if not (svPath and outPath) then
  io.stderr:write("usage: lua gen_seasonloot.lua <savedvars.lua> <out.lua>\n")
  os.exit(1)
end

-- Load the SavedVariables (sets the global MythicLootGlobalDB).
local chunk = assert(loadfile(svPath))
chunk()
local db = assert(MythicLootGlobalDB, "no MythicLootGlobalDB in file")
local loot = assert(db.seasonLoot, "no seasonLoot in DB")
local stamp = db.seasonLootStamp or {}

-- Sorted keys so output is deterministic (clean diffs across regenerations).
local function sortedKeys(t)
  local keys = {}
  for k in pairs(t) do keys[#keys + 1] = k end
  table.sort(keys)
  return keys
end

local out = {}
local function w(s) out[#out + 1] = s end

w("-- AUTO-GENERATED by /ml export (ADR 0009). DO NOT EDIT BY HAND.")
w("-- Source: the Encounter Journal, read through MythicLoot's own reader -- never")
w("-- another addon (ADR 0001). Regenerate each season: /ml export, then run")
w("-- tools/gen_seasonloot.lua over the exported SavedVariables.")
w(string.format("-- Stamp: build %s, M+ season %s.",
  tostring(stamp.toc), tostring(stamp.season)))
w("local ADDON_NAME, MythicLoot = ...")
w("")
w("MythicLoot.SeasonLootStamp = { toc = " .. tostring(stamp.toc or 0)
  .. ", season = " .. tostring(stamp.season or 0) .. " }")
w("")
w("-- [classID][specID][challengeMapID] = { {id, slot, name, icon}, ... }")
w("MythicLoot.SeasonLoot = {")

local nItems = 0
for _, classID in ipairs(sortedKeys(loot)) do
  w("[" .. classID .. "]={")
  local bySpec = loot[classID]
  for _, specID in ipairs(sortedKeys(bySpec)) do
    w("[" .. specID .. "]={")
    local byMap = bySpec[specID]
    for _, mapID in ipairs(sortedKeys(byMap)) do
      w("[" .. mapID .. "]={")
      for _, it in ipairs(byMap[mapID]) do
        nItems = nItems + 1
        w(string.format("{id=%d,slot=%q,name=%q,icon=%d},",
          it.id, tostring(it.slot), tostring(it.name), it.icon or 0))
      end
      w("},")
    end
    w("},")
  end
  w("},")
end
w("}")
w("")

local fh = assert(io.open(outPath, "w"))
fh:write(table.concat(out, "\n"))
fh:close()

io.stderr:write(string.format("wrote %s — %d classes, %d item rows\n",
  outPath, #sortedKeys(loot), nItems))
